services:
  app:
    container_name: url-shortener-app
    build: .
    ports:
      - "3001:3000"
    environment:
      APP_PORT: 3000
    volumes:
      - ./public:/public
      - ./views:/views
      - ./i18n:/i18n
    depends_on:
      - db

  db:
    container_name: url-shortener-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: gorm
      POSTGRES_USER: gorm
      POSTGRES_DB: gorm
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: ~
